// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVM48vW4hnc8EEcY4dRy23QJEqtyxMomM',
    appId: '1:500837717207:web:723bab4da32835165ccc92',
    messagingSenderId: '500837717207',
    projectId: 'survey-app-ef141',
    authDomain: 'survey-app-ef141.firebaseapp.com',
    storageBucket: 'survey-app-ef141.appspot.com',
    measurementId: 'G-RVDHSRCLQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIYGDidSY46UJzfoM_3gTXgOODuKS6aTc',
    appId: '1:500837717207:android:da3d7b84732ff5c35ccc92',
    messagingSenderId: '500837717207',
    projectId: 'survey-app-ef141',
    storageBucket: 'survey-app-ef141.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB24zTt58lgo5LiGptJIh38Xh_Gor9LKr4',
    appId: '1:500837717207:ios:cea8b1be212be4cc5ccc92',
    messagingSenderId: '500837717207',
    projectId: 'survey-app-ef141',
    storageBucket: 'survey-app-ef141.appspot.com',
    iosClientId: '500837717207-e0phgoo9pr18jldvtjomhh0oj95fuqdo.apps.googleusercontent.com',
    iosBundleId: 'com.survey.app',
  );
}
